### ISSUE TITLE
How to access the hdfs file system from another spark container in docker?

### ISSUE THREAD

**Issue by aliabbasjp** [intropro/single-node-cloudera-env#6]
I need to access this running cloudera single node hdfs file system from external container running SPARK, how to do that? or how to integerate this with other SPARK containers?

**Comment by ownport** [comment]
If the Spark container is located on the same host with Spark container you can get access to HDFS by container IP address. If Spark container is located on another host, you can expose ports for HDFS service compose.yml file according to http://blog.cloudera.com/blog/2009/08/hadoop-default-ports-quick-reference/ and get access to HDFS service by host IP address

**Comment by ddenyshchenko** [comment]
Also you can simplify your work with all services without exposing ports. In order to do this you should use net: "host" mode:
1. check if all ports used by all services inside this docker are free 
2. in docker-compose.yml comment hostname and ports fileds
3. in docker-compose.yml uncomment net: "host"
4. run - docker-compose run -d
5. check status - docker-compose logs
6. after cdh was deployed all services ports inside container will be listened on your machine's ip address

**Comment by aliabbasjp** [comment]
@ddenyshchenko what if the some of the ports used by this container are not free in the host ? and do I need tp restart this container after updating the yml file? if yes how?  run - docker-compose run -d is sufficient?

**Comment by ddenyshchenko** [comment]
@aliabbasjp if you use "net: host" mode docker puts container into hosts network stack and you should be guided by rules for none containerized processes, that is you can't use ports that are not free. If you can't free needed ports just use default net mod and ports exposing.
